apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 501432864658.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 501432864658.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 47aa5dd8
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
